name: green_sm_nyc
version: "0.1.0"
config-version: 2
profile: green_sm_nyc

vars:
  analysis_start_date: "2023-01-01"
  analysis_end_date: "2026-01-01"

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

require-dbt-version: [">=1.9.0", "<2.0.0"]

models:
  green_sm_nyc:
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: intermediate
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
